version: 3.4.{build}
branches:
  only:
  - master
  - test_appveyor
  - lto
  - msvc
skip_tags: true
os: Windows Server 2012 R2
clone_depth: 8
clone_folder: C:\hb\
build:
  verbosity: detailed

environment:
  GITHUB_TOKEN:
    secure: EAvrbP8pR3X0XMvu+PtEpAsTS5hh7jWZl5T+6sLOuCUqmyTLxNY8P2JPYMidRbpf
  VIRUSTOTAL_APIKEY:
    secure: TdJYONfrpH45DuyKxraVqgHYy25IQ/F8TKHzYf+u5zz1aiM2yR0YTMaGxyj2EMReEearSI9kD9D2ZykybSVEbRyEaotZlceUb2lPDKELl3M=
  PUSHOVER_USER:
    secure: r0t3XEOacCfk+DgkHyrg5yXc6rXbxTMTCNZfgyIfgmY=
  PUSHOVER_TOKEN:
    secure: DjWTkh5sUw6dUQkHv3KhTvi2llF9GN17z60h9kRGYX4=

  NGHTTP2_VER: 1.6.0
  NGHTTP2_HASH_32: c9c102c8e42b21f048740263ec29dc3845601343aea402089016f9e7792b0a78
  NGHTTP2_HASH_64: d4b3e9035d1af237df3fd77049f602d7dc8459d2ce9764dd6a1395bca26f9f4d
  OPENSSL_VER: 1.0.2e
  OPENSSL_HASH_32: 5247ef88294f873e81f31012e947fbb9cfc45ef5048070345cd0b25df5d0a4a3
  OPENSSL_HASH_64: 378c05aa9752a49619d092d3968382b1f03bceb4fb258b77b2e54c997cb038be
  LIBSSH2_VER: 1.6.0
  LIBSSH2_HASH_32: 534dc5a0e67d272ec5926238e58e481f21814ad80f25b75be81d04716ac8cc15
  LIBSSH2_HASH_64: eb56b8b9c049fe3e990f0cfe5a187c1a60cf48023cdfb7931e2e0831324144d9
  CURL_VER: 7.46.0
  CURL_HASH_32: 470e7b5177e1f1acf2f7dc936067efc02faa662676ba8d524f47e6f8f3157a8d
  CURL_HASH_64: 2aea48b8d4e1698a68b005cdb7d721b49cdc3553e1786ffd5164dfa2622891f2

install:
  - sh -c ./package/mpkg_win_dl.sh

build_script:
  - set HB_VF=daily
  - set HB_RT=%APPVEYOR_BUILD_FOLDER%
  - set HB_MKFLAGS=clean install HB_VERSION=%HB_VF%
  - if "%APPVEYOR_REPO_BRANCH%" == "lto" set HB_BASE=64
  - if not "%HB_BASE%" == "64" set HB_SFX_7Z=%HB_RT%\7zsfx\7zsd_All.sfx
# - if     "%HB_BASE%" == "64" set HB_SFX_7Z=%HB_RT%\7zsfx\7zsd_All_x64.sfx
  - set HB_DIR_7Z=%HB_RT%\7z\
  - set HB_DIR_UPX=%HB_RT%\upx\
  - set HB_DIR_MINGW=%HB_RT%\mingw64
  - set HB_DIR_OPENSSL_32=%HB_RT%\openssl-mingw32\
  - set HB_DIR_OPENSSL_64=%HB_RT%\openssl-mingw64\
  - set HB_DIR_LIBSSH2_32=%HB_RT%\libssh2-mingw32\
  - set HB_DIR_LIBSSH2_64=%HB_RT%\libssh2-mingw64\
  - set HB_DIR_NGHTTP2_32=%HB_RT%\nghttp2-mingw32\
  - set HB_DIR_NGHTTP2_64=%HB_RT%\nghttp2-mingw64\
  - set HB_DIR_CURL_32=%HB_RT%\curl-mingw32\
  - set HB_DIR_CURL_64=%HB_RT%\curl-mingw64\
  - set _ORI_PATH=%PATH%

  # common settings

  - if "%APPVEYOR_REPO_BRANCH%" == "lto" set HB_BUILD_CONTRIBS=hbrun hbformat/utils hbct hbcurl hbhpdf hbmzip hbwin hbsqlit3 hbtip hbssl hbexpat hbmemio rddsql hbzebra sddsqlt3 sddodbc hbunix hbmisc hbmxml hbcups hbtest hbtcpio hbcomio hbcrypto hbnetio hbpipeio hbgzio hbbz2io
  - set HB_BUILD_STRIP=bin
  - set HB_BUILD_PKG=yes
  - set _HB_BUILD_PKG_ARCHIVE=no

  # can disable to save time/space

  - if not "%APPVEYOR_REPO_BRANCH%" == "msvc" set _HB_BUNDLE_3RDLIB=yes
  - set HB_INSTALL_3RDDYN=yes
  - set HB_BUILD_CONTRIB_DYN=yes
  - set HB_BUILD_POSTRUN=".\hbtest -noenv" ".\hbspeed --noenv --stdout"

  # debug

# - set HB_BUILD_CONTRIBS=no
# - set HB_MKFLAGS=%HB_MKFLAGS% HB_BUILD_OPTIM=no
# - set HB_BUILD_VERBOSE=yes
# - set _HB_PKG_DEBUG=yes
# - set _HB_BUNDLE_3RDLIB=yes

  # mingw

  - if "%APPVEYOR_REPO_BRANCH%" == "lto" set HB_USER_CFLAGS=%HB_USER_CFLAGS% -flto -ffat-lto-objects
  - if not "%APPVEYOR_REPO_BRANCH%" == "msvc" if "%HB_BUILD_MODE%" == "cpp" set HB_USER_LDFLAGS=%HB_USER_LDFLAGS% -static-libgcc -static-libstdc++

  - set HB_COMPILER=mingw
  - set HB_CPU=x86
  - set HB_WITH_CURL=%HB_DIR_CURL_32%include
  - set HB_WITH_OPENSSL=%HB_DIR_OPENSSL_32%include
# - set HB_WITH_QT=%HB_RT%\Qt\5.4\mingw491_32\include
  - set PATH=%HB_DIR_MINGW%\bin;%_ORI_PATH%
  - if not "%APPVEYOR_REPO_BRANCH%" == "msvc" win-make.exe %HB_MKFLAGS%

  - set HB_COMPILER=mingw64
  - set HB_CPU=x86_64
  - set HB_WITH_CURL=%HB_DIR_CURL_64%include
  - set HB_WITH_OPENSSL=%HB_DIR_OPENSSL_64%include
  - set HB_WITH_QT=
  - set PATH=%HB_DIR_MINGW%\bin;%_ORI_PATH%
  - if not "%APPVEYOR_REPO_BRANCH%" == "msvc" win-make.exe %HB_MKFLAGS%

  # msvc

  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_USER_CFLAGS=
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_USER_LDFLAGS=

# - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set _HB_MSVC_ANALYZE=yes
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_COMPILER=
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_CPU=
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_WITH_CURL=
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_WITH_OPENSSL=
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set HB_WITH_QT=%HB_RT%\Qt\5.4\msvc2013_64_opengl\include

  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set PATH=%_ORI_PATH%
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" win-make.exe %HB_MKFLAGS%

  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" set PATH=%_ORI_PATH%
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" if exist "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - if "%APPVEYOR_REPO_BRANCH%" == "msvc" win-make.exe %HB_MKFLAGS%

  # packaging

  - sh -c ./package/mpkg_win.sh

artifacts:
  - path: harbour-daily-win.7z*
    name: pkg-win

deploy:
  - provider: GitHub
    auth_token: $(github_token)
    tag: v3.4.0dev
    release: 'Harbour 3.4.0dev daily'
    description: 'Snapshot build generated after each commit.'
    artifact: pkg-win
    draft: false
    prerelease: true
    on:
      branch: master
      appveyor_repo_tag: false
  - provider: Local
    on:
      branch: test_appveyor

after_deploy:
  - if not "%_HB_BUNDLE_3RDLIB%" == "yes" curl -sS -X POST https://www.virustotal.com/vtapi/v2/file/scan --form "apikey=%VIRUSTOTAL_APIKEY%" --form file=@harbour-daily-win.7z.exe
